name: "curiejet integration"
version: "1.1.3"
slug: "curiejet_integration"
description: "This Home Assistant add-on listens to MQTT messages and dynamically generates 
  MQTT Discovery configurations for CurieJet devices (e.g., ZP2, ZH1). 
  It enables seamless integration of sensor and control data from various CurieJet models 
  into your Home Assistant setup."
startup: "services"
boot: "auto"
arch:
  - aarch64
  - amd64
  - armv7
url: "https://github.com/YJ-spec/my-addon-repo"
init: false
ingress: false

# 刪掉 volumes
# volumes:
#   - /share:/share  

# 正確的 mounts
mounts:
  - source: share
    target: /share
    type: bind
    read_only: false

options:
  mqtt_topics: "+/+/data,+/+/control"
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  HA_LONG_LIVED_TOKEN: ""

schema:
  mqtt_topics: str
  mqtt_broker: str
  mqtt_port: int
  mqtt_username: str?
  mqtt_password: str?
  HA_LONG_LIVED_TOKEN: str?
