name: "My Test Add-on"
version: "1.0.8"
slug: "my_addon"
description: "A test add-on with MQTT support"
startup: "services"
boot: "auto"
arch:
  - aarch64
  - amd64
  - armv7
url: "https://github.com/YJ-spec/my-addon-repo"
init: false
ingress: false

options:
  mqtt_topics: "+/+/data,+/+/control"
  mqtt_broker: "localhost"
  mqtt_port: 1883
  mqtt_username: "your_user"
  mqtt_password: "your_pass"

schema:
  mqtt_topics: str
  mqtt_broker: str
  mqtt_port: int
