name: "My Test Add-on"
version: "1.0.18"
slug: "my_addon"
description: "A test add-on with MQTT support"
startup: "services"
boot: "auto"
arch:
  - aarch64
  - amd64
  - armv7
url: "https://github.com/YJ-spec/my-addon-repo"
init: false
ingress: false

options:
  mqtt_topics: "+/+/data,+/+/control"
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  HA_LONG_LIVED_TOKEN: ""

schema:
  mqtt_topics: str
  mqtt_broker: str
  mqtt_port: int
  mqtt_username: str?
  mqtt_password: str?
  HA_LONG_LIVED_TOKEN: str?
